grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3
model_selection:
  module_0:
    class: KNeighborsClassifier
    module: sklearn.neighbors
    params:
      algorithm: kd_tree
      weights: uniform
      n_neighbors: 3
    search_param_grid:
      algorithm:
        - auto
        - ball_tree
        - kd_tree
        - brute
      weights:
        - uniform
        - distance
      n_neighbors:
        - 3
        - 5
        - 9


  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      max_depth: 10
      max_features: sqrt
      n_estimators: 3
    search_param_grid:
      max_depth:
        - 10
        - 15
        - 20
      max_features:
        - sqrt
        - log2
      n_estimators:
        - 3
        - 5
        - 9


  module_2:
    class: DecisionTreeClassifier
    module: sklearn.tree
    params:
      max_depth: 5
      criterion: gini
      min_samples_split: 2
    search_param_grid:
      max_depth:
        - 5
        - 10
        - 15
      criterion:
        - gini
        - entropy
      min_samples_split:
        - 2
        - 5
        - 10


  module_3:
    class: GradientBoostingClassifier
    module: sklearn.ensemble
    params:
      n_estimators: 50   # Select one default value
      learning_rate: 0.05  # Select one default value
      max_depth: 3  # Select one default value
    search_param_grid:
      n_estimators:
        - 50
        - 100
        - 200
      learning_rate:
        - 0.05
        - 0.1
        - 0.2
      max_depth:
        - 3
        - 5
        - 7

  module_4:
    class: LogisticRegression
    module: sklearn.linear_model
    params:
      penalty: l2
      C: 1.0
    search_param_grid:
      penalty:
        - l2
      C:
        - 0.1
        - 1
        - 10


  module_5:
    class: XGBClassifier
    module: xgboost
    params:
      max_depth: 3            # Select a default value
      learning_rate: 0.05     # Select a default value
      n_estimators: 50        # Select a default value
    search_param_grid:
      max_depth:
        - 3
        - 5
        - 7
      learning_rate:
        - 0.05
        - 0.1
        - 0.2
      n_estimators:
        - 50
        - 100
        - 200


  module_6:
    class: CatBoostClassifier
    module: catboost
    params:
      depth: 6           # Select a default value
      learning_rate: 0.03    # Select a default value
      iterations: 50         # Select a default value
    search_param_grid:
      depth:
        - 6
        - 8
        - 10
      learning_rate:
        - 0.03
        - 0.1
        - 0.2
      iterations:
        - 50
        - 100
        - 200


  module_7:
    class: SVC
    module: sklearn.svm
    params:
      C: 1.0         # Select a default value
      kernel: linear  # Select a default value
    search_param_grid:
      C:
        - 0.1
        - 1
        - 10
      kernel:
        - linear
        - poly
        - rbf

  module_8:
    class: AdaBoostClassifier
    module: sklearn.ensemble
    params:
      n_estimators: 50        # Select a default value
      learning_rate: 0.05     # Select a default value
    search_param_grid:
      n_estimators:
        - 50
        - 100
        - 200
      learning_rate:
        - 0.05
        - 0.1
        - 0.2

